#define PICOSAT_CC "gcc"
#define PICOSAT_CFLAGS "-O03 -fomit-frame-pointer -fno-common -DLOCAL -DETAB_FLATCOPY -DSATURATION_USES_FOLDING_LABELS -DFOLD -DPRINT_DOT_STEPS -DBIGJUMP     -Wall   -g   -DPRINT_SOMEERRORS_STDOUT -DMEMORY_RESERVE_PARANOID -DPRINT_TSTP_STATUS -DSTACK_SIZE=32768 -DCLAUSE_PERM_IDENT -DTAGGED_POINTERS  -std=gnu99 -I../include"
#define PICOSAT_VERSION "965"
